name: fireflutter
description: "A Flutter framework that works with Firebase, providing beautiful UI and ready-to-use app logic."
version: 0.4.0
homepage: https://github.com/thruthesky/fireflutter
screenshots:
  - description: A fast and reliable app development toolkit.
    path: etc/logo/logo.jpg

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  date_picker_v2: ^0.0.4
  devicelocale: ^0.7.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  memory_cache: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
